language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
script:
  - python setup.py build_ext --inplace
  # Temporary solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - make test
