language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install -r requirements_py`python -c 'import sys; print(str(sys.version_info[0]) + str(sys.version_info[1]))'`.txt --use-mirrors"
script:
  # Temporary solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - make test
